package com.james.tinkerscalibration.contents;

import com.james.tinkerscalibration.TinkersCalibration;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.core.registries.Registries;
import net.neoforged.neoforge.registries.DeferredRegister;
import slimeknights.mantle.registration.RegistryObject;

public class TinkersCalibrationBlocks {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(Registries.BLOCK, TinkersCalibration.MODID);
    private static final BlockBehaviour.Properties ORE = BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(2.5F, 5f).sound(SoundType.STONE);
    private static final BlockBehaviour.Properties METAL = Block.Properties.of().requiresCorrectToolForDrops().strength(5F, 1200f).sound(SoundType.METAL);
    public static RegistryObject<Block> lindsteel_block = RegistryObject.of(BLOCKS.register("lindsteel_block", () -> new Block(METAL)));
    public static RegistryObject<Block> emperorslime_block = RegistryObject.of(BLOCKS.register("emperorslime_block", () -> new Block(METAL)));
    public static RegistryObject<Block> fazelle_block = RegistryObject.of(BLOCKS.register("fazelle_block", () -> new Block(METAL)));
    public static RegistryObject<Block> titanium_block = RegistryObject.of(BLOCKS.register("titanium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> jazz_block = RegistryObject.of(BLOCKS.register("jazz_block", () -> new Block(METAL)));
    public static RegistryObject<Block> mandite_block = RegistryObject.of(BLOCKS.register("mandite_block", () -> new Block(METAL)));
    public static RegistryObject<Block> deepslate_titanium_ore = RegistryObject.of(BLOCKS.register("deepslate_titanium_ore", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> titanium_ore = RegistryObject.of(BLOCKS.register("titanium_ore", () -> new Block(ORE)));
    public static RegistryObject<Block> stellarium_ore = RegistryObject.of(BLOCKS.register("stellarium_ore", () -> new Block(ORE)));
    public static RegistryObject<Block> immersed_silver_ore = RegistryObject.of(BLOCKS.register("immersed_silver_ore", () -> new Block(ORE)));
    public static RegistryObject<Block> inert_witherium_ore = RegistryObject.of(BLOCKS.register("inert_witherium_ore", () -> new Block(ORE)));
    public static RegistryObject<Block> hothium_ore = RegistryObject.of(BLOCKS.register("hothium_ore", () -> new Block(ORE)));
    public static RegistryObject<Block> magiga_ore = RegistryObject.of(BLOCKS.register("magiga_ore", () -> new Block(ORE)));
    public static RegistryObject<Block> tonium_ore = RegistryObject.of(BLOCKS.register("tonium_ore", () -> new Block(ORE)));
    public static RegistryObject<Block> corundum_ore = RegistryObject.of(BLOCKS.register("corundum_ore", () -> new DropExperienceBlock(UniformInt.of(4,8), ORE)));
    public static RegistryObject<Block> nitre_ore = RegistryObject.of(BLOCKS.register("nitre_ore", () -> new DropExperienceBlock(UniformInt.of(1,4), ORE)));
    //public static RegistryObject<Block> pyrophyllite_ore = RegistryObject.of(BLOCKS.register("pyrophyllite_ore", () -> new DropExperienceBlock(UniformInt.of(2,5), ORE)));
    public static RegistryObject<Block> spinel_ore = RegistryObject.of(BLOCKS.register("spinel_ore", () -> new DropExperienceBlock(UniformInt.of(4,8), ORE)));
    public static RegistryObject<Block> talcum_ore = RegistryObject.of(BLOCKS.register("talcum_ore", () -> new DropExperienceBlock(UniformInt.of(1,4), ORE)));
    public static RegistryObject<Block> tourmaline_ore = RegistryObject.of(BLOCKS.register("tourmaline_ore", () -> new DropExperienceBlock(UniformInt.of(1,4), ORE)));
    //public static RegistryObject<Block> sunstone_ore = RegistryObject.of(BLOCKS.register("sunstone_ore", () -> new DropExperienceBlock(UniformInt.of(4,8), ORE)));
    //public static RegistryObject<Block> moonstone_ore = RegistryObject.of(BLOCKS.register("moonstone_ore", () -> new DropExperienceBlock(UniformInt.of(4,8), ORE)));
    public static RegistryObject<Block> vibrating_crystal_ore = RegistryObject.of(BLOCKS.register("vibrating_crystal_ore", () -> new DropExperienceBlock(UniformInt.of(2,6), ORE)));
    public static RegistryObject<Block> deepslate_stellarium_ore = RegistryObject.of(BLOCKS.register("deepslate_stellarium_ore", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> deepslate_immersed_silver_ore = RegistryObject.of(BLOCKS.register("deepslate_immersed_silver_ore", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> deepslate_hothium_ore = RegistryObject.of(BLOCKS.register("deepslate_hothium_ore", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> deepslate_magiga_ore = RegistryObject.of(BLOCKS.register("deepslate_magiga_ore", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> deepslate_tonium_ore = RegistryObject.of(BLOCKS.register("deepslate_tonium_ore", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> deepslate_corundum_ore = RegistryObject.of(BLOCKS.register("deepslate_corundum_ore", () -> new DropExperienceBlock(UniformInt.of(4,8), BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> deepslate_nitre_ore = RegistryObject.of(BLOCKS.register("deepslate_nitre_ore", () -> new DropExperienceBlock(UniformInt.of(1,4), BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    //public static RegistryObject<Block> deepslate_pyrophyllite_ore = RegistryObject.of(BLOCKS.register("deepslate_pyrophyllite_ore", () -> new DropExperienceBlock(UniformInt.of(2,5), ORE)));
    public static RegistryObject<Block> deepslate_spinel_ore = RegistryObject.of(BLOCKS.register("deepslate_spinel_ore", () -> new DropExperienceBlock(UniformInt.of(4,8), BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> deepslate_talcum_ore = RegistryObject.of(BLOCKS.register("deepslate_talcum_ore", () -> new DropExperienceBlock(UniformInt.of(1,4), BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> deepslate_tourmaline_ore = RegistryObject.of(BLOCKS.register("deepslate_tourmaline_ore", () -> new DropExperienceBlock(UniformInt.of(1,4), BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    //public static RegistryObject<Block> deepslate_sunstone_ore = RegistryObject.of(BLOCKS.register("deepslate_sunstone_ore", () -> new DropExperienceBlock(UniformInt.of(4,8), ORE)));
    //public static RegistryObject<Block> deepslate_moonstone_ore = RegistryObject.of(BLOCKS.register("deepslate_moonstone_ore", () -> new DropExperienceBlock(UniformInt.of(4,8), ORE)));
    public static RegistryObject<Block> deepslate_vibrating_crystal_ore = RegistryObject.of(BLOCKS.register("deepslate_vibrating_crystal_ore", () -> new DropExperienceBlock(UniformInt.of(2,6), BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.DEEPSLATE))));
    public static RegistryObject<Block> stellarium_block = RegistryObject.of(BLOCKS.register("stellarium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> immersed_silver_block = RegistryObject.of(BLOCKS.register("immersed_silver_block", () -> new Block(METAL)));
    public static RegistryObject<Block> inert_witherium_block = RegistryObject.of(BLOCKS.register("inert_witherium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> halleium_block = RegistryObject.of(BLOCKS.register("halleium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> hothium_block = RegistryObject.of(BLOCKS.register("hothium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> steamium_block = RegistryObject.of(BLOCKS.register("steamium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> magiga_block = RegistryObject.of(BLOCKS.register("magiga_block", () -> new Block(METAL)));
    public static RegistryObject<Block> tonium_block = RegistryObject.of(BLOCKS.register("tonium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> oraclium_block = RegistryObject.of(BLOCKS.register("oraclium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> witherium_block = RegistryObject.of(BLOCKS.register("witherium_block", () -> new Block(METAL)));
    public static RegistryObject<Block> alumite_block = RegistryObject.of(BLOCKS.register("alumite_block", () -> new Block(METAL)));
    public static RegistryObject<Block> corundum_block = RegistryObject.of(BLOCKS.register("corundum_block", () -> new Block(METAL)));
    public static RegistryObject<Block> nitre_block = RegistryObject.of(BLOCKS.register("nitre_block", () -> new Block(METAL)));
    //public static RegistryObject<Block> pyrophyllite_block = RegistryObject.of(BLOCKS.register("pyrophyllite_block", () -> new Block(METAL)));
    public static RegistryObject<Block> spinel_block = RegistryObject.of(BLOCKS.register("spinel_block", () -> new Block(METAL)));
    public static RegistryObject<Block> talcum_block = RegistryObject.of(BLOCKS.register("talcum_block", () -> new Block(METAL)));
    public static RegistryObject<Block> tourmaline_block = RegistryObject.of(BLOCKS.register("tourmaline_block", () -> new Block(METAL)));
    //public static RegistryObject<Block> sunstone_block = RegistryObject.of(BLOCKS.register("sunstone_block", () -> new Block(METAL)));
    //public static RegistryObject<Block> moonstone_block = RegistryObject.of(BLOCKS.register("moonstone_block", () -> new Block(METAL)));
    public static RegistryObject<Block> vibrating_crystal_block = RegistryObject.of(BLOCKS.register("vibrating_crystal_block", () -> new Block(METAL)));
    public static RegistryObject<Block> iceland_spar_block = RegistryObject.of(BLOCKS.register("iceland_spar_block", () -> new Block(METAL)));
    public static RegistryObject<Block> lizanite_block = RegistryObject.of(BLOCKS.register("lizanite_block", () -> new Block(METAL)));
    public static RegistryObject<Block> topaz_block = RegistryObject.of(BLOCKS.register("topaz_block", () -> new Block(METAL)));
    public static RegistryObject<Block> prehnite_block = RegistryObject.of(BLOCKS.register("prehnite_block", () -> new Block(METAL)));

}
