modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Thanks all the tinkers, especially Beidou-Shen, la_ji, Wumutu, JihandeMoyingren, chuangxiang2333, and smartgenius5558!"
authors="${mod_authors}"
description='''
This is Tinkers' Calibration, a mod that calibrates something about Tinkers' Construct and adds more!
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tconstruct"
    type="required"
    versionRange="[3.12.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mantle"
    type="required"
    versionRange="[1.12.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="twilightforest"
    type="optional"
    versionRange="[4.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="projecte"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
